/* Configuration for lsp_client generated by Alire */
#ifndef LSP_CLIENT_CONFIG_H
#define LSP_CLIENT_CONFIG_H

#define CRATE_VERSION "0.1.0-dev"
#define CRATE_NAME "lsp_client"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "aarch64"

#define ALIRE_HOST_DISTRO "ubuntu"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
